### ISSUE TITLE
Fedora Compatibility

### ISSUE THREAD

**Issue by luciodaou** [nonamed01/fuckForticlient#4]
Hello,

Having some issues with Fedora.

Fedora uses group `wheel` instead of `sudo`:
https://github.com/nonamed01/fuckForticlient/blob/8cf807473c586134c0e3f145accea9b7495fde3f/fuckForticlient.sh#L349

Also, it doesn't have `dpkg`:
https://github.com/nonamed01/fuckForticlient/blob/8cf807473c586134c0e3f145accea9b7495fde3f/fuckForticlient.sh#L433
https://github.com/nonamed01/fuckForticlient/blob/8cf807473c586134c0e3f145accea9b7495fde3f/fuckForticlient.sh#L604

**Comment by nonamed01** [comment]
Well, this script was meant for Debian and Debian-derivatives, so this is not really an issue. Feel free to modify it for Redhat and derivatives..... Cheers!

**Comment by luciodaou** [comment]
No problem! Managed to make it work with Fedora changed the lines mentioned above, but some extra steps were needed. Will try to document everything and send a PR.

Thank you so much for the amazing work with this script. It's absolutely fantastic.
